### ISSUE TITLE
permalink setting ignored

### ISSUE THREAD

**Issue by ecupaio** [mnyrop/pagemaster#5]
If I add a permalink field to the settings, it's ignored. Ex)
_permalink_
blog/title/date

_config_
blog:
  output: true
  id_key: title
  permalink: permalink_field

_output_
blog/title.html

**Comment by mnyrop** [comment]
Hi @ecupaio, 

Pagemaster currently generates permalink fields based on the name of the collection and the global permalink setting in `_config.yml`, e.g. `permalink: pretty`. 

If I understand correctly, this is a feature request to add a `--no-permalink` option (or equivalent), so that permalinks are handled by Jekyll defaults. Is that right?

**Comment by ecupaio** [comment]
yes indeed. I just want my custom permalinks so tag this however you like and do your thing. Other than that, this is a really great plugin.

**Comment by mnyrop** [comment]
Hi @ecupaio, try the newest version by adding 
```ruby
group :jekyll_plugins do
  gem 'pagemaster', :git => 'https://github.com/mnyrop/pagemaster', :branch => 'no-perma'
end
```
to your Gemfile + running the pagemaster command with the option `--no-permalink`, e.g.
```sh
$ bundle exec jekyll pagemaster --no-permalink [collection-name]
```
and let me know if it does what you're hoping? If so I will merge + release as 2.0.1.

**Comment by ecupaio** [comment]
that did the trick! Sorry for the delay

**Comment by mnyrop** [comment]
#6
